### ISSUE TITLE
Русская локализация

### ISSUE THREAD

**Issue by dakotarisen** [laytya/EavesDrop#1]
Доброе утро!Могли бы вы добавить русскую локализацию этому замечательному аддону?

**Comment by Artur91425** [comment]
Перевел
[EavesDrop_ruRU.zip](https://github.com/laytya/EavesDrop/files/911439/EavesDrop_ruRU.zip)
laytya, я еще добавил локаль для строки "EavesDrop Options". 
781 строка в EavesDrop.lua

P.S. А зачем там библиотека Waterfall-1.0? Она в этом аддоне вообще не нужна, можно смело удалить.

**Comment by laytya** [comment]
Ну она изначальна была в этом аддоне на ТБС я просто бакпортнул - вообще там много настроек, а я терпеть не могу дьюдроп менюшки . С Ниагарой то понятно что не нужна.

**Comment by laytya** [comment]
added in 1.4.1
